spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/habitpact
spring.datasource.username=root
spring.datasource.password=killersanju2001@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true